name: LocalOps Deploy
description: Github Action to trigger a deployment in LocalOps deliver
author: LocalOps

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  base_url:
    description: The base URL of the API
    required: false
    default: 'https://sdk.localops.co'
  api_token:
    description: The API token for authentication
    required: true
  environment_id:
    description: The environment ID for deployment
    required: true
  service_id:
    description: The service ID for deployment
    required: true
  commit_id:
    description:
      The commit ID to deploy (one of commit_id, docker_image_tag, or helm_chart_version must be
      provided)
    required: false
  docker_image_tag:
    description:
      The docker image tag to deploy (one of commit_id, docker_image_tag, or helm_chart_version must
      be provided)
    required: false
  helm_chart_version:
    description:
      The helm chart version to deploy (one of commit_id, docker_image_tag, or helm_chart_version
      must be provided)
    required: false

runs:
  using: node24
  main: dist/index.js
